cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800
spring:
    datasource:
        url: jdbc:mysql://121.41.27.6:3306/sumec_wechat
        username: wechat
        password: wechat123!
        driverClassName: com.mysql.jdbc.Driver
jwt:
    TTLMillis: 3600000
    audience: "测试系统"
    base64Security: "bas
    e64"
server:
    port: 8011
