cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800

jwt:
    TTLMillis: 3600000
    audience: "测试系统"
    base64Security: "bas
    e64"
server:
    port: 8011
spring:
  data:
    mongodb:
      database: alienlabnews
      uri: mongodb://zhuliang:zhuliang@127.0.0.1:27017/alienlabnews